In [2]:
import numpy as np

In [3]:
# day 35
gh = np.array([[[4,5,6],[6,7,8]],[[9,10,11],[12,13,14]],[[15,16,17],[18,19,61]]])
gh

array([[[ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 61]]])

In [4]:
#           0   1   2
# 0---->[[[ 4,  5,  6],   0
#         [ 6,  7,  8]],  1

# 1----> [[ 9, 10, 11],   0
#         [12, 13, 14]],  1

# 2----> [[15, 16, 17],   0
#         [18, 19, 61]]]  

In [5]:
print(gh[0,0,0])  # (depth,row,col)

4


In [6]:
print(gh[0,1,0:2])

[6 7]


In [7]:
print(gh[1,1,1:])

[13 14]


In [8]:
print(gh[2,1,1:])

[19 61]


In [9]:
# [[16,17],[19,61]]
print(gh[2,0:,1:])

[[16 17]
 [19 61]]


In [10]:
# [15,16,17]
print(gh[2,0,0:])

[15 16 17]


In [11]:
# [[9,10],[12,13]]
print(gh[1,0:,0:2])

[[ 9 10]
 [12 13]]


In [12]:
# reshape

y = np.array([[1,2,3],[4,5,6],[9,8,7],[0,0,0]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [0, 0, 0]])

In [13]:
# here there are 12 elements
# to reshape we should have the multiples of 12
# that is , row,col wise : 1*12 , 
                        #  12*1
                        #  2*6
                        #  6*2
                        #  3*4
                        #  4*3
# so here we can have combinations like this only where the product is 12.

In [14]:
y.reshape([3,4])    # it is possible bcoz 3*4 = 12


array([[1, 2, 3, 4],
       [5, 6, 9, 8],
       [7, 0, 0, 0]])

In [15]:
y.reshape([6,2])  # here 6 * 2 = 12


array([[1, 2],
       [3, 4],
       [5, 6],
       [9, 8],
       [7, 0],
       [0, 0]])

In [16]:
# now , if we have to reshape into 3D , a new element adds.
# its the depth, and altogether it should be 12
# so here i can we combinations like : 1*6*2
                                    #  1*2*6
                                    #  2*1*6
                                    #  2*12*1
                                    #  3*4*1
                                    #  4*3*1
                                    #  2*12*1

In [17]:
y.reshape([1,6,2])


array([[[1, 2],
        [3, 4],
        [5, 6],
        [9, 8],
        [7, 0],
        [0, 0]]])

In [18]:
y.reshape([2,6,1])


array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[9],
        [8],
        [7],
        [0],
        [0],
        [0]]])

In [19]:
y.reshape([3,1,4])


array([[[1, 2, 3, 4]],

       [[5, 6, 9, 8]],

       [[7, 0, 0, 0]]])

In [20]:
y.reshape([4,3,1])


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[9],
        [8],
        [7]],

       [[0],
        [0],
        [0]]])

In [22]:
y.reshape([12,1,1])


array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[9]],

       [[8]],

       [[7]],

       [[0]],

       [[0]],

       [[0]]])

In [23]:
y.reshape([6,2,1])


array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[9],
        [8]],

       [[7],
        [0]],

       [[0],
        [0]]])