In [3]:
import numpy as np

In [4]:
# day 35
gh = np.array([[[4,5,6],[6,7,8]],[[9,10,11],[12,13,14]],[[15,16,17],[18,19,61]]])
gh

array([[[ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 61]]])

In [5]:
#           0   1   2
# 0---->[[[ 4,  5,  6],   0
#         [ 6,  7,  8]],  1

# 1----> [[ 9, 10, 11],   0
#         [12, 13, 14]],  1

# 2----> [[15, 16, 17],   0
#         [18, 19, 61]]]  

In [6]:
print(gh[0,0,0])

4


In [7]:
print(gh[0,1,0:2])

[6 7]


In [8]:
print(gh[1,1,1:])

[13 14]


In [9]:
print(gh[2,1,1:])

[19 61]


In [10]:
# [[16,17],[19,61]]
print(gh[2,0:,1:])

[[16 17]
 [19 61]]


In [11]:
# [15,16,17]
print(gh[2,0,0:])

[15 16 17]


In [12]:
# [[9,10],[12,13]]
print(gh[1,0:,0:2])

[[ 9 10]
 [12 13]]
