In [1]:
import numpy as np

In [ ]:
# zeros
# 1D
gh = np.zeros(6,dtype=int)
gh

array([0, 0, 0, 0, 0, 0])

In [3]:
# 2D
# if dtype is not specified it is taken as float
gy = np.zeros([4,5],dtype=int)
gy

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
# 3D

jk = np.zeros([2,3,4])
jk

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
datas = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[0,0,0]])
datas

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  0,  0]])

In [6]:
# max
datas.max()

np.int64(12)

In [7]:
print("largest element in row wise",datas.max(axis=1))
# to get the largest element in row wise

largest element in row wise [ 3  6  9 12  0]


In [8]:
print("largest element in column wise",datas.max(axis=0))
# to get the largest element in column wise

largest element in column wise [10 11 12]


In [12]:
# min
print("smallest value in the matrix is ",datas.min())

smallest value in the matrix is  0


In [10]:
print("smallest element in row wise",datas.min(axis=1))
# to get the smallest element in row wise

smallest element in row wise [ 1  4  7 10  0]


In [11]:
print("smallest element in column wise",datas.min(axis=0))
# to get the smallest element in column wise

smallest element in column wise [0 0 0]


In [13]:
# argmax()
print("The index which has maximum value is ",datas.argmax())

The index which has maximum value is  11


In [16]:
print("In row wise the index with the highest element",datas.argmax(axis=1))

In row wise the index with the highest element [2 2 2 2 0]


In [15]:
print("In column wise the index with the highest element",datas.argmax(axis=0))

In column wise the index with the highest element [3 3 3]


In [17]:
# argmin()
print("The index which has minimum value is ",datas.argmin())

The index which has minimum value is  12


In [18]:
print("In row wise the index with the smallest element",datas.argmin(axis=1))

In row wise the index with the smallest element [0 0 0 0 0]


In [19]:
print("In column wise the index with the smallest element",datas.argmin(axis=0))

In column wise the index with the smallest element [4 4 4]


In [20]:
ku = np.array([[1,2],[2,4],[5,6],[7,8]])
ku
# (4,2)

array([[1, 2],
       [2, 4],
       [5, 6],
       [7, 8]])

In [21]:
lk = np.array([[9,8],[1,5],[6,7],[5,4]])
lk
# (4,2)

array([[9, 8],
       [1, 5],
       [6, 7],
       [5, 4]])

In [22]:
# matrix addition : both matrix should be of same size
ku + lk 

array([[10, 10],
       [ 3,  9],
       [11, 13],
       [12, 12]])

In [23]:
# matrix subtraction : both matrix should be of same size
ku - lk

array([[-8, -6],
       [ 1, -1],
       [-1, -1],
       [ 2,  4]])

In [24]:
# matrix multiplication : both matrix should be of same size
ku * lk

array([[ 9, 16],
       [ 2, 20],
       [30, 42],
       [35, 32]])

In [25]:
# matrix division : both matrix should be of same size
ku / lk

array([[0.11111111, 0.25      ],
       [2.        , 0.8       ],
       [0.83333333, 0.85714286],
       [1.4       , 2.        ]])

In [26]:
# 1. create a 1D NumPy array of 10 zeros

n = np.zeros(10,dtype=int)
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
# 2. create a 3x3 matrix filled with zeros

m = np.zeros([3,3],dtype=int)
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
# 3. create a 2x4x3 array of zeros and print its shape

d = np.zeros([2,4,3],dtype=int)
d

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [29]:
d.shape

(2, 4, 3)

In [ ]:
# 4. create a zero array with the same shape as np.arange(12).reshape(3,4)
# zeros like is used to get the shape of a alredy specified array
# t = np.zeros([3,4],dtype=int)
t = np.arange(12).reshape(3,4)
tp = np.zeros_like(t)
tp

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
# 6. create a array from 1 to 20 and find the maximum value
k = np.arange(1,21)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
k.max()


np.int64(20)

In [ ]:
# 7. create a random 4x4 array and find :
# overall maximum
# maximum in each row
# maximum in each column
# l = np.arange(16).reshape(4,4) another way to create
l = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
l

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
l.shape


(4, 4)

In [35]:
l.max()


np.int64(16)

In [48]:
print("The maximum value in each row is ",l.max(axis=1))


The maximum value in each row is  [ 4  8 12 16]


In [49]:
print("The maximum value in each column is ",l.max(axis=0))

The maximum value in each column is  [13 14 15 16]


In [38]:
# 8. Find the minimum value in a 3x5 array
j = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
j

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
j.shape


(3, 5)

In [40]:
j.min()


np.int64(1)

In [41]:
# 9. what is the difference between max and min in an array of numbers from 10 to 50
k = np.arange(10,51)
k

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [42]:
k.min()


np.int64(10)

In [43]:
k.max()


np.int64(50)

In [44]:
k.max() - k.min()


np.int64(40)

In [45]:
# 10. Generate 15 random numbers and print the smallest value

p = np.array([1,5,4,3,8,7,2,11,86,54,32,0,21,25,72])
p

array([ 1,  5,  4,  3,  8,  7,  2, 11, 86, 54, 32,  0, 21, 25, 72])

In [46]:
p.shape


(15,)

In [47]:
p.min()


np.int64(0)

In [51]:
# 11.	Create an array [10, 25, 5, 40, 30] and find:
# •	Index of maximum value
# •	Index of minimum value

k = np.array([10,25,5,40,30])
k

array([10, 25,  5, 40, 30])

In [52]:
print("Index of the maximum value is",k.argmax())


Index of the maximum value is 3


In [53]:
print("Index of the minimum value is",k.argmin())


Index of the minimum value is 2


In [54]:
# 12.	Create a 3×3 matrix and find:
# •	Position (index) of the largest element
# •	Position (index) of the smallest element

l = np.arange(9).reshape(3,3)
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
print("Index of the maximum value is",l.argmax())


Index of the maximum value is 8


In [56]:
print("Index of the minimum value is",l.argmin())


Index of the minimum value is 0


In [57]:
# 13.	In a random 5×5 array, find the index of maximum value in each row.

m = np.arange(25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
print("The index of maximum value in each row is ",m.argmax(axis=1))


The index of maximum value in each row is  [4 4 4 4 4]


In [59]:
# 14.	What does argmax() return if there are duplicate maximum values? (Test with example)

k = np.array([[2,3,4],[8,5,3],[8,7,2],[8,6,5]])
k

array([[2, 3, 4],
       [8, 5, 3],
       [8, 7, 2],
       [8, 6, 5]])

In [60]:
print("The index of maximum value where the array contain duplicates is ",k.argmax())
# it returns the first index of the maximum value

The index of maximum value where the array contain duplicates is  3


In [61]:
# 15.	Find the index of minimum value in a 1D array and then print the value using that index.
p = np.array([5,8,3,6,7])
p

array([5, 8, 3, 6, 7])

In [62]:
p.argmin()

np.int64(2)