In [1]:
import numpy as np

In [ ]:
# zeros
# 1D
gh = np.zeros(6,dtype=int)
gh

array([0, 0, 0, 0, 0, 0])

In [3]:
# 2D
# if dtype is not specified it is taken as float
gy = np.zeros([4,5],dtype=int)
gy

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
# 3D

jk = np.zeros([2,3,4])
jk

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])