In [1]:
import numpy as np

In [ ]:
# zeros
# 1D
gh = np.zeros(6,dtype=int)
gh

array([0, 0, 0, 0, 0, 0])

In [3]:
# 2D
# if dtype is not specified it is taken as float
gy = np.zeros([4,5],dtype=int)
gy

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
# 3D

jk = np.zeros([2,3,4])
jk

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
datas = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[0,0,0]])
datas

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  0,  0]])

In [6]:
# max
datas.max()

np.int64(12)

In [7]:
print("largest element in row wise",datas.max(axis=1))
# to get the largest element in row wise

largest element in row wise [ 3  6  9 12  0]


In [8]:
print("largest element in column wise",datas.max(axis=0))
# to get the largest element in column wise

largest element in column wise [10 11 12]


In [12]:
# min
print("smallest value in the matrix is ",datas.min())

smallest value in the matrix is  0


In [10]:
print("smallest element in row wise",datas.min(axis=1))
# to get the smallest element in row wise

smallest element in row wise [ 1  4  7 10  0]


In [11]:
print("smallest element in column wise",datas.min(axis=0))
# to get the smallest element in column wise

smallest element in column wise [0 0 0]


In [13]:
# argmax()
print("The index which has maximum value is ",datas.argmax())

The index which has maximum value is  11


In [16]:
print("In row wise the index with the highest element",datas.argmax(axis=1))

In row wise the index with the highest element [2 2 2 2 0]


In [15]:
print("In column wise the index with the highest element",datas.argmax(axis=0))

In column wise the index with the highest element [3 3 3]


In [17]:
# argmin()
print("The index which has minimum value is ",datas.argmin())

The index which has minimum value is  12


In [18]:
print("In row wise the index with the smallest element",datas.argmin(axis=1))

In row wise the index with the smallest element [0 0 0 0 0]


In [19]:
print("In column wise the index with the smallest element",datas.argmin(axis=0))

In column wise the index with the smallest element [4 4 4]


In [20]:
ku = np.array([[1,2],[2,4],[5,6],[7,8]])
ku
# (4,2)

array([[1, 2],
       [2, 4],
       [5, 6],
       [7, 8]])

In [21]:
lk = np.array([[9,8],[1,5],[6,7],[5,4]])
lk
# (4,2)

array([[9, 8],
       [1, 5],
       [6, 7],
       [5, 4]])

In [22]:
# matrix addition : both matrix should be of same size
ku + lk 

array([[10, 10],
       [ 3,  9],
       [11, 13],
       [12, 12]])

In [23]:
# matrix subtraction : both matrix should be of same size
ku - lk

array([[-8, -6],
       [ 1, -1],
       [-1, -1],
       [ 2,  4]])

In [24]:
# matrix multiplication : both matrix should be of same size
ku * lk

array([[ 9, 16],
       [ 2, 20],
       [30, 42],
       [35, 32]])

In [25]:
# matrix division : both matrix should be of same size
ku / lk

array([[0.11111111, 0.25      ],
       [2.        , 0.8       ],
       [0.83333333, 0.85714286],
       [1.4       , 2.        ]])