In [1]:
import numpy as np

In [ ]:
# zeros
# 1D
gh = np.zeros(6,dtype=int)
gh

array([0, 0, 0, 0, 0, 0])

In [3]:
# 2D
# if dtype is not specified it is taken as float
gy = np.zeros([4,5],dtype=int)
gy

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
# 3D

jk = np.zeros([2,3,4])
jk

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
datas = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[0,0,0]])
datas

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  0,  0]])

In [6]:
# max
datas.max()

np.int64(12)

In [7]:
print("largest element in row wise",datas.max(axis=1))
# to get the largest element in row wise

largest element in row wise [ 3  6  9 12  0]


In [8]:
print("largest element in column wise",datas.max(axis=0))
# to get the largest element in column wise

largest element in column wise [10 11 12]


In [12]:
# min
print("smallest value in the matrix is ",datas.min())

smallest value in the matrix is  0


In [10]:
print("smallest element in row wise",datas.min(axis=1))
# to get the smallest element in row wise

smallest element in row wise [ 1  4  7 10  0]


In [11]:
print("smallest element in column wise",datas.min(axis=0))
# to get the smallest element in column wise

smallest element in column wise [0 0 0]


In [13]:
# argmax()
print("The index which has maximum value is ",datas.argmax())

The index which has maximum value is  11


In [16]:
print("In row wise the index with the highest element",datas.argmax(axis=1))

In row wise the index with the highest element [2 2 2 2 0]


In [15]:
print("In column wise the index with the highest element",datas.argmax(axis=0))

In column wise the index with the highest element [3 3 3]
