<a href="https://colab.research.google.com/github/Nandanalinson/Python-core-concepts/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# day 33

In [1]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.4
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                         

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])   # to create an array
a

array([1, 2, 3, 4, 5])

In [4]:
a.ndim    # to get the dimension of the array

1

In [5]:
print(type(a))  # to get the type

<class 'numpy.ndarray'>


In [6]:
b = np.array([1,2,3,4,"hello"])   # all the values are converted to string
b

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [7]:
b.dtype

dtype('<U21')

In [8]:
c = np.array([1,2,4.5,6,7]) # here all are converted to float ----> int , float , string (order)
c

array([1. , 2. , 4.5, 6. , 7. ])

In [9]:
b.size       # to get the no of elements

5

In [10]:
# two dimensional array
ab = np.array([[1,2],[2,3],[3,4]])
ab

array([[1, 2],
       [2, 3],
       [3, 4]])

In [11]:
ab.shape  # (row,col) here 3 row and 2 col

(3, 2)

In [12]:
ab.ndim   # two dimension

2

In [13]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])   # 2D array
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
d.ndim

2

In [15]:
#3D array
three_d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
three_d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
three_d.shape   # (depth,row,col)   here depth is 2 , and in each depth the row and col is counted. so in first dept the no of rows is 2 and cols is 2

(2, 2, 2)

In [17]:
three_d.ndim

3

In [18]:
three_d.size

8

In [19]:
three_di = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])   # the rows and cols in each depth should be the same
three_di

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
three_di.shape    # (depth,row,col)   here depth is 3 , and in each depth the row and col is counted. so in first dept the no of rows is 2 and cols is 2

(3, 2, 2)

In [21]:
three_di.size

12

In [22]:
# 2D with shape (2,4)

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr.shape

(2, 4)

In [24]:
# 3D array with shape (2,3,3)
ar = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
ar

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
ar.shape

(2, 3, 3)

In [ ]:
# day 34

In [26]:
# numpy arrays are:
# faster
# memory efficient
# support mathematical operation directly

# list ia a basic array

# images are stored as arrays

# feature       list           array

# speed         slower         faster

# data type     can store       usually same data type
              # mixed datatypes

# math operation  cannot directly   can directly

# used in         general python   AI,ML,Data science

In [27]:
# 1D
# forward indexing
# backward indexing
y = np.array([1,2,3,4,5,6])
y

array([1, 2, 3, 4, 5, 6])

In [28]:
y.shape

(6,)

In [29]:
y.ndim

1

In [30]:
y[0]

np.int64(1)

In [31]:
print(y[0])   # forward indexing

1


In [32]:
print(y[-1])    # backward indexing

6


In [33]:
print(y[1:3])   # slicing

[2 3]


In [34]:
# [3,4,5]

print(y[2:5])

[3 4 5]


In [35]:
# [5]
print(y[-2])

5


In [36]:
# [4,5,6]
print(y[3:])

[4 5 6]


In [37]:
# 2D
h = np.array([[1,2,5],[2,3,7],[3,4,8],[5,6,9]])
h

array([[1, 2, 5],
       [2, 3, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [38]:
print(h[0])

[1 2 5]


In [39]:
print(h[0][0])

1


In [40]:
print(h[1][1])

3


In [41]:
print(h[2,1:])

[4 8]


In [42]:
print(h[3,0:2])

[5 6]


In [43]:
print(h[3,0])

5


In [44]:
# [3,4]
print(h[2,0:2])

[3 4]


In [45]:
# [5,6]
print(h[3,0:2])

[5 6]


In [46]:
# [[3 4]
#  [5 6]]
print(h[2:,0:2])

[[3 4]
 [5 6]]


In [47]:
print(h[1:,2:])

[[7]
 [8]
 [9]]


In [48]:
print(h[1:,1:])

[[3 7]
 [4 8]
 [6 9]]


In [49]:
print(h[1:3,1:])

[[3 7]
 [4 8]]


In [50]:
print(h[0:,0:2])

[[1 2]
 [2 3]
 [3 4]
 [5 6]]


In [51]:
print(h[0:,0:1])

[[1]
 [2]
 [3]
 [5]]


In [52]:
k = np.array([[1,2,3,4],[4,5,6,7],[9,8,10,11]])
k

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9,  8, 10, 11]])

In [53]:
# [4,5,6,7]
print(k[1])

[4 5 6 7]


In [54]:
# [5,6],[8,10]
print(k[1:,1:3])

[[ 5  6]
 [ 8 10]]


In [55]:
# [6,7],[10,11]
print(k[1:,2:])

[[ 6  7]
 [10 11]]


In [56]:
# 5
print(k[1,1])

5


In [57]:
# [10,11]
print(k[2,2:])

[10 11]


In [58]:
# [9,8]
print(k[2,0:2])

[9 8]


In [59]:
kl = np.arange(1,101,2)     #(start,stop,step)
kl

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [60]:
#  print multiples of 3
kp = np.arange(3,101,3)
kp

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [61]:
# reshape
jk = np.array([[1,2,3,4],[4,5,6,7],[9,8,6,5]])
jk

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [9, 8, 6, 5]])

In [62]:
jk.reshape([4,3])

array([[1, 2, 3],
       [4, 4, 5],
       [6, 7, 9],
       [8, 6, 5]])

In [63]:
jk.reshape([2,6])

array([[1, 2, 3, 4, 4, 5],
       [6, 7, 9, 8, 6, 5]])

In [64]:
# create one dimensional array multiples of 4 upto 40
pi = np.arange(4,41,4)
pi
# convert it in possible 2 dimensional shapes

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [65]:
pi.reshape([5,2])

array([[ 4,  8],
       [12, 16],
       [20, 24],
       [28, 32],
       [36, 40]])

In [66]:
# day 35
gh = np.array([[[4,5,6],[6,7,8]],[[9,10,11],[12,13,14]],[[15,16,17],[18,19,61]]])
gh

array([[[ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 61]]])

In [ ]:
#           0   1   2
# 0---->[[[ 4,  5,  6],   0
#         [ 6,  7,  8]],  1

# 1----> [[ 9, 10, 11],   0
#         [12, 13, 14]],  1

# 2----> [[15, 16, 17],   0
#         [18, 19, 61]]]  1

In [67]:
print(gh[0,0,0])     # (depth,row,col)

4


In [69]:
print(gh[0,1,0:2])

[6 7]


In [72]:
print(gh[1,1,1:])

[13 14]


In [73]:
print(gh[2,1,1:])

[19 61]


In [74]:
# [[16,17],[19,61]]
print(gh[2,0:,1:])

[[16 17]
 [19 61]]


In [75]:
# [15,16,17]
print(gh[2,0,0:])

[15 16 17]


In [76]:
# [[9,10],[12,13]]
print(gh[1,0:,0:2])

[[ 9 10]
 [12 13]]


In [77]:
print(gh[0,0:,2])

[6 8]


In [78]:
# reshape

y = np.array([[1,2,3],[4,5,6],[9,8,7],[0,0,0]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [0, 0, 0]])

In [79]:
# here there are 12 elements
# to reshape we should have the multiples of 12
# that is , row,col wise : 1*12 ,
                        #  12*1
                        #  2*6
                        #  6*2
                        #  3*4
                        #  4*3
# so here we can have combinations like this only where the product is 12.

In [80]:
y.reshape([3,4])    # it is possible bcoz 3*4 = 12

array([[1, 2, 3, 4],
       [5, 6, 9, 8],
       [7, 0, 0, 0]])

In [81]:
y.reshape([6,2])  # here 6 * 2 = 12

array([[1, 2],
       [3, 4],
       [5, 6],
       [9, 8],
       [7, 0],
       [0, 0]])

In [82]:
# now , if we have to reshape into 3D , a new element adds.
# its the depth, and altogether it should be 12
# so here i can we combinations like : 1*6*2
                                    #  1*2*6
                                    #  2*1*6
                                    #  2*12*1
                                    #  3*4*1
                                    #  4*3*1
                                    #  2*12*1
                                    #  2*3*2
                                    #  3*2*2

In [83]:
y.reshape([1,6,2])

array([[[1, 2],
        [3, 4],
        [5, 6],
        [9, 8],
        [7, 0],
        [0, 0]]])

In [84]:
y.reshape([2,6,1])

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]],

       [[9],
        [8],
        [7],
        [0],
        [0],
        [0]]])

In [85]:
y.reshape([3,1,4])

array([[[1, 2, 3, 4]],

       [[5, 6, 9, 8]],

       [[7, 0, 0, 0]]])

In [86]:
y.reshape([4,3,1])

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[9],
        [8],
        [7]],

       [[0],
        [0],
        [0]]])

In [87]:
y.reshape([12,1,1])

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[9]],

       [[8]],

       [[7]],

       [[0]],

       [[0]],

       [[0]]])

In [88]:
y.reshape([6,2,1])

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[9],
        [8]],

       [[7],
        [0]],

       [[0],
        [0]]])

In [89]:
y.reshape([2,3,2])

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[9, 8],
        [7, 0],
        [0, 0]]])

In [90]:
y.reshape([3,2,2])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [9, 8]],

       [[7, 0],
        [0, 0]]])

In [91]:
# create a 1D NumPy array containing all multiplies oof 4 upto 40
# print the array

r = np.arange(4,41,4)
r

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [92]:
# print its shape
r.shape

(10,)

In [94]:
# create a 1D array of even numbers from 2 to 20
n = np.arange(2,21,2)
n

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [95]:
# convert it into a 2 * 5 matrix # reshape
n.reshape([2,5])

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [97]:
# create a 1D array with numbers from 1 to 12
m = np.arange(1,13)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
# convert it into a 3 * 4 matrix # reshape
m.reshape([3,4])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
# what will happen if you try to reshape a 10-element array into shape (3,4)?
# answer : ValueError: cannot reshape array of size 10 into shape (3,4)
n.reshape([3,4])

ValueError: cannot reshape array of size 10 into shape (3,4)

In [101]:
# create a 1D array with multiples of 5 upto 50.
# find all possible 2D shapes
# Reshape the array into any two valid 2D shapes

l = np.arange(5,51,5)
l

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [102]:
# all possible 2d shapes are : 2*5
                            #  5*2
                            #  10*1
                            #  1*10

In [103]:
l.reshape([2,5])

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [105]:
l.reshape([10,1])

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [107]:
# create a 1D array with 24 elements.
# convert it into :
# (2,3,4)
# (4,3,2)
# (6,2,2)

p = np.arange(1,25)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [108]:
p.shape

(24,)

In [109]:
p.reshape([2,3,4])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [110]:
p.reshape([4,3,2])


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [111]:
p.reshape([6,2,2])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24]]])

In [112]:
# create a 1D array from 1 to 18
o = np.arange(1,19)
o

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [113]:
o.shape

(18,)

In [114]:
# convert it into all possible 3D shapes
o.reshape([3,6,1])

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16],
        [17],
        [18]]])

In [115]:
o.reshape([3,3,2])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [116]:
o.reshape([2,3,3])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])